### ISSUE TITLE
Path is too long: "ExceptionStatusComponent$ExceptionStatusComponentListener.class"

### ISSUE THREAD

**Issue by cjwidd** [googlesamples/tango-examples-unity#15]
I'm getting hit with an error when building these unity examples:

DirectoryNotFoundException: Could not find a part of the path "C:\Users\Christopher\Desktop\tango-examples-unity-master\ExperimentalProjects\MeshBuilder\Assets\Plugins\Android\tango-ux-support-library\bin\classes\com\google\atap\tango\ux\components\ExceptionStatusComponent$ExceptionStatusComponentListener.class" or "Temp\StagingArea\android-libraries\tango-ux-support-library\bin\classes\com\google\atap\tango\ux\components\ExceptionStatusComponent$ExceptionStatusComponentListener.class"

I followed the path and it does exist.

I've had very mixed results, ranging from being able to build the point cloud, area learning, and motion tracking examples, but not the experimental examples, to being able to build the examples but the axes are rotated improperly. It's a mess.

**Comment by chaosemer** [comment]
The full path to the Temp copy is two characters over Windows' PATH_MAX, which is likely causing this issue. Please shorten the folder name to your repo, just eliminating master will likely be fine.

I'm closing this issue right now since this is so old, but feel free to reopen if you are still having issues.
