### ISSUE TITLE
Problem With Tango Application, Crashes On Startup

### ISSUE THREAD

**Issue by BMARX123** [googlesamples/tango-examples-unity#47]
Application used to work on older software revisions, but now crashes on startup. Here is the error I am receiving:

`I/ActivityManager(  900): Start proc com.OwlArrowGames.TangoSportsVR for activity com.OwlArrowGames.TangoSportsVR/com.google.unity.GoogleUnityActivity: pid=5029 uid=10118 gids={50118, 3003, 1028, 1015}

D/AndroidRuntime( 5029): Shutting down VM

E/AndroidRuntime( 5029): FATAL EXCEPTION: main

E/AndroidRuntime( 5029): Process: com.OwlArrowGames.TangoSportsVR, PID: 5029

E/AndroidRuntime( 5029): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.OwlArrowGames.TangoSportsVR/com.google.unity.GoogleUnityActivity}: java.lang.ClassNotFoundException: Didn't find class "com.google.unity.GoogleUnityActivity" on path: DexPathList[[zip file "/data/app/com.OwlArrowGames.TangoSportsVR-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.OwlArrowGames.TangoSportsVR-2, /system/lib, /vendor/lib, /system/lib]]

E/AndroidRuntime( 5029):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2122)

E/AndroidRuntime( 5029):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2246)

E/AndroidRuntime( 5029):    at android.app.ActivityThread.access$800(ActivityThread.java:136)

E/AndroidRuntime( 5029):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1197)

E/AndroidRuntime( 5029):    at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime( 5029):    at android.os.Looper.loop(Looper.java:136)

E/AndroidRuntime( 5029):    at android.app.ActivityThread.main(ActivityThread.java:5030)

E/AndroidRuntime( 5029):    at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 5029):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)

E/AndroidRuntime( 5029):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)

E/AndroidRuntime( 5029): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.unity.GoogleUnityActivity" on path: DexPathList[[zip file "/data/app/com.OwlArrowGames.TangoSportsVR-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.OwlArrowGames.TangoSportsVR-2, /system/lib, /vendor/lib, /system/lib]]

E/AndroidRuntime( 5029):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

E/AndroidRuntime( 5029):    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)

E/AndroidRuntime( 5029):    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

E/AndroidRuntime( 5029):    at android.app.Instrumentation.newActivity(Instrumentation.java:1061)

E/AndroidRuntime( 5029):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2113)

E/AndroidRuntime( 5029):    ... 9 more

E/AndroidRuntime( 5029):    Suppressed: java.lang.ClassNotFoundException: com.google.unity.GoogleUnityActivity

E/AndroidRuntime( 5029):        at java.lang.Class.classForName(Native Method)

E/AndroidRuntime( 5029):        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)

E/AndroidRuntime( 5029):        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)

E/AndroidRuntime( 5029):        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

E/AndroidRuntime( 5029):        ... 12 more

E/AndroidRuntime( 5029):    Caused by: java.lang.NoClassDefFoundError: Class "Lcom/google/unity/GoogleUnityActivity;" not found

E/AndroidRuntime( 5029):        ... 16 more

W/ActivityManager(  900):   Force finishing activity com.OwlArrowGames.TangoSportsVR/com.google.unity.GoogleUnityActivity`

**Comment by rodrigodzf** [comment]
I have a similar problem. I can't play any example scenes using unity 5.4.0b21 and the latest TangoSDK. Btw I saw your post in [http://stackoverflow.com/questions/37822590/unity-android-application-unable-to-load-native-library-and-failed-to-mkdirat](url) I see your logcat is different here. Did you get to solve this other issue? Here is mine:

**E/cutils  (  155): Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
W/Vold    (  155): Returning OperationFailed - no handler for errno 30
W/ContextImpl( 8544): Failed to ensure directory: /storage/sdcard1/Android/obb/com.projecttango.unityexamples
E/cutils  (  155): Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
W/Vold    (  155): Returning OperationFailed - no handler for errno 30
W/ContextImpl( 8544): Failed to ensure directory: /storage/sdcard1/Android/data/com.projecttango.unityexamples/files
W/NativeActivity( 8544): ANativeActivity_onCreate not found
D/AndroidRuntime( 8544): Shutting down VM
E/AndroidRuntime( 8544): FATAL EXCEPTION: main
E/AndroidRuntime( 8544): Process: com.projecttango.unityexamples, PID: 8544
E/AndroidRuntime( 8544): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.projecttango.unityexamples/com.google.unity.GoogleUnityActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/app-lib/com.projecttango.unityexamples-2/libmain.so
E/AndroidRuntime( 8544):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2196)
E/AndroidRuntime( 8544):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2246)
E/AndroidRuntime( 8544):    at android.app.ActivityThread.access$800(ActivityThread.java:136)
E/AndroidRuntime( 8544):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1197)
E/AndroidRuntime( 8544):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8544):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 8544):    at android.app.ActivityThread.main(ActivityThread.java:5030)
E/AndroidRuntime( 8544):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8544):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime( 8544):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
E/AndroidRuntime( 8544): Caused by: java.lang.IllegalArgumentException: Unable to load native library: /data/app-lib/com.projecttango.unityexamples-2/libmain.so
E/AndroidRuntime( 8544):    at android.app.NativeActivity.onCreate(NativeActivity.java:186)
E/AndroidRuntime( 8544):    at com.google.unity.GoogleUnityActivity.onCreate(GoogleUnityActivity.java:44)
E/AndroidRuntime( 8544):    at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 8544):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 8544):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160)
E/AndroidRuntime( 8544):    ... 9 more
W/ActivityManager(  904):   Force finishing activity com.projecttango.unityexamples/com.google.unity.GoogleUnityActivity**

**Comment by BMARX123** [comment]
This is the issue I am having now. Sucks to see others having the same problem. Shoot the Tango team an email at their help address and see if they can help you. Still waiting on another response for mine. Glad they've decided to have a ton of problems near the launch of the first consumer device...

**Comment by kkukshtel** [comment]
Having this same issue as well. I heard something about it working in Unity 5.3 so I'm testing the new SDK with that version now and will report back.

**Comment by BMARX123** [comment]
Awesome, let us know if it works!

**Comment by kkukshtel** [comment]
Hey — Someone in our studio just tried with 5.3 and the error went away! Still not sure what the issue is but can confirm it works.

**Comment by Jiaxin-li** [comment]
Meet the same problem Unity 5.4.1f1 
Log:
I/PowerServiceCient(  901): Successfully bound to service
E/cutils  (  155): Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
W/Vold    (  155): Returning OperationFailed - no handler for errno 30
W/ContextImpl( 6775): Failed to ensure directory: /storage/sdcard1/Android/obb/com.GoldenRidge.NavAdmAl
E/cutils  (  155): Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
W/ContextImpl( 6775): Failed to ensure directory: /storage/sdcard1/Android/data/com.GoldenRidge.NavAdmAl/files
W/Vold    (  155): Returning OperationFailed - no handler for errno 30
W/NativeActivity( 6775): ANativeActivity_onCreate not found
D/AndroidRuntime( 6775): Shutting down VM
E/AndroidRuntime( 6775): FATAL EXCEPTION: main
E/AndroidRuntime( 6775): Process: com.GoldenRidge.NavAdmAl, PID: 6775
E/AndroidRuntime( 6775): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.GoldenRidge.NavAdmAl/com.google.unity.GoogleUnityActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/app-lib/com.GoldenRidge.NavAdmAl-1/libmain.so
E/AndroidRuntime( 6775):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2196)
E/AndroidRuntime( 6775):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2246)
E/AndroidRuntime( 6775):        at android.app.ActivityThread.access$800(ActivityThread.java:136)
E/AndroidRuntime( 6775):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1197)
E/AndroidRuntime( 6775):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6775):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 6775):        at android.app.ActivityThread.main(ActivityThread.java:5030)
E/AndroidRuntime( 6775):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6775):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime( 6775):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
E/AndroidRuntime( 6775): Caused by: java.lang.IllegalArgumentException: Unable to load native library: /data/app-lib/com.GoldenRidge.NavAdmAl-1/libmain.so
E/AndroidRuntime( 6775):        at android.app.NativeActivity.onCreate(NativeActivity.java:186)
E/AndroidRuntime( 6775):        at com.google.unity.GoogleUnityActivity.onCreate(GoogleUnityActivity.java:44)
E/AndroidRuntime( 6775):        at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 6775):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 6775):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160)
E/AndroidRuntime( 6775):        ... 9 more
W/ActivityManager(  901):   Force finishing activity com.GoldenRidge.NavAdmAl/com.google.unity.GoogleUnityActivity
D/Sensors (  901): Writing packet 54 36 0A 00 74
D/Sensors (  901): Writing packet 54 31 0A 00 74
W/ActivityManager(  901): Activity pause timeout for ActivityRecord{65489aa0 u0 com.GoldenRidge.NavAdmAl/com.google.unity.GoogleUnityActivity t11 f}
D/Raydium_ts_main(  257): ## Report rate in 10 seconds =1171
                    E/WindowManager(  901): Starting window AppWindowToken{658cc228 token=Token{65304740 ActivityRecord{65489aa0 u0 com.GoldenRidge.NavAdmAl/com.google.unity.GoogleUnityActivity t11}}} timed out
W/ActivityManager(  901): Activity destroy timeout for ActivityRecord{65489aa0 u0 com.GoldenRidge.NavAdmAl/com.google.unity.GoogleUnityActivity t11 f}
E/WifiController(  901): Not handled here 155652
D/WifiController(  901): battery changed pluggedType: 2

**Comment by ramoliahiten** [comment]
I have same problem.. game is crashing in MI-Pad device.
unity 5.2.2p4
for admob i am using,  game play service 9.4.0

**Comment by chaosemer** [comment]
We've fixed similar issues around this over the past few months but neglected to check in with this issue. Is this still a problem for people?

**Comment by chaosemer** [comment]
Seems like the issue is solved. Please reopen if this is still an issue for you.
