### ISSUE TITLE
App fails to startup when integrating GVR Spatial Audio

### ISSUE THREAD

**Issue by andrewnakas** [googlesamples/tango-examples-unity#69]
Following the GVR Tango integration guide, I am able to get Tango working with the GVR sdk. Everything works as expected until I add the GVR Spatial Audio, which causes a crash on startup. I did temporarily get Spatial audio working with the native oculus package in unity, but it's definitely not as powerful and just does not feel as immersive as it should be.  Any insight?

I'm not sure if I got the event in here, but here is a link to some log cat.
https://docs.google.com/document/d/1yYsfU-nG6WlgNb-7mvCwxasDtYfUqCZ1jxMQZrJLFPo/edit?usp=sharing

Thanks! Stoked on GVR!

**Comment by bopangzz** [comment]
Which version of Unity you are using?

**Comment by andrewnakas** [comment]
I've been able to reproduce the crash with both 5.5 and 5.6. I also tried to get it running with both gvr 1.1.0 and .8.5.

**Comment by bopangzz** [comment]
I think the issue you are seeing is caused by the conflict in GoogleUnityActivity. Both Tango SDK and GVR SDK includes an aar file that contains a GoogleUnityActivity and they are different. I think GVR audio can be used without using the unitygvractivity.aar. You can try to only keep the gvr audio stuff and delete the rest pieces in gvr sdk in you project and try to make it work with Tango sdk.

**Comment by andrewnakas** [comment]
Awsome! Thanks for the insight! Right now I just need the spatialized audio and tango, but in the future, I'll need audio, tango and cardboard all working together. I'm assuming this aar conflict would get fixed in the future, and until then I think I can use unity's spatial audio with gvr and tango fine.  Appreciate it!
